name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"

      - name: Drop artifact
        uses: actions/upload-artifact@v3
        with:
          name: "drop"
          path: "main.pdf"
